INSERT INTO institutions(name,  description) VALUES ("Dbam o zdrowie", "Pomoc dzieciom z ubogich rodzin.");
INSERT INTO institutions(name,  description) VALUES ("A kogo", "Pomoc wybudzaniu dzieci ze śpiączki.");
INSERT INTO institutions(name,  description) VALUES ("Dla dzieci", "Pomoc osobom znajduącym się w trudnej sytuacji życiowej.");
INSERT INTO institutions(name,  description) VALUES ("Bez domu", "Pomoc dla osób nie posiadających miejsca zamieszkania.");
INSERT INTO categories(name) VALUES ("ubrania, które nadają się do ponownego użycia");
INSERT INTO categories(name) VALUES ("ubrania do wyrzucenia");
INSERT INTO categories(name) VALUES ("zabawki");
INSERT INTO categories(name) VALUES ("książki");
INSERT INTO categories(name) VALUES ("inne");
INSERT INTO `roles` (`id`, `name`) VALUES (NULL, 'ROLE_USER');
INSERT INTO `roles` (`id`, `name`) VALUES (NULL, 'ROLE_ADMIN');